Script "stack_aeFieldTest_card_id_1002"

/*
# Name: card id 1002 of stack "aeFieldTest"
# ID: card id 1002 of stack "aeFieldTest"
# Hash: 1TtKFeZDVdd3V5IDyPbndA==
*/


--on openStack
--   if "animationEngine" is not among the lines of the stacksInUse then
--      if "animationEngine" is not among the lines of the openstacks then
--         start using stack (specialFolderPath("resources") &  "/animationEngine.livecode")
--      else
--         answer error "Animation Engine must be in use for this to work !" as sheet
--      end if
--   end if
--end openStack
